# Generated by Django 2.2.6 on 2019-11-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191101_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(null=True, to='shop.Product'),
        ),
    ]
