# Generated by Django 2.2.6 on 2019-11-04 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191104_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
