# Generated by Django 2.2.6 on 2019-11-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Twoja opinia'),
        ),
    ]
